galaxy_info:
  author: Alan Tai
  description: Install Git
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - git
    - scm
    - vcs
    - versioning
dependencies: []
