galaxy_info:
  author: Alan Tai
  description: Install JDK
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - java
    - jdk
    - jvm
dependencies: []
