---
- name: Add certbot repository
  become: true
  apt_repository:
    repo: ppa:certbot/certbot
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Install certbot
  become: true
  apt:
    name: certbot
    update_cache: yes
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
