galaxy_info:
  author: Alan Tai
  description: Clean up apt cache
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - ubuntu
    - apt
    - clean
dependencies: []
