---
- name: Copy InstrumentalD configuration
  template:
    src: instrumentald.toml.j2
    dest: /etc/instrumentald.toml
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart InstrumentalD
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
