---
- name: Add AdoptOpenJDK repository
  apt_repository:
    repo: ppa:rpardini/adoptopenjdk

- name: Install JDK
  become: true
  apt:
    name: adoptopenjdk-11-jdk-openj9-installer
    update_cache: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
