---
- name: Copy Grafana configuration file
  become: true
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Grafana
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
