---
- name: Copy jail.local
  become: true
  copy:
    src: jail.ini
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Fail2ban
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Copy fail2ban.local
  become: true
  copy:
    src: fail2ban.ini
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Fail2ban
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
