---
- name: Install prerequisites
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - software-properties-common
      - curl
      - wget
      - unzip
      - jq
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Install Ubuntu LivePatch
  become: true
  snap:
    name: canonical-livepatch
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Enable Ubuntu LivePatch service
  become: true
  command: "canonical-livepatch enable {{ ubuntu_livepatch_key }}"
