---
- name: Install prerequisites
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - software-properties-common
      - curl
      - wget
      - unzip
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
