---
- name: Ensure path exists for Stackdriver credentials
  become: true
  file:
    path: "{{ gcp_stackdriver_credentials_dir }}"
    state: directory
    recurse: yes

- name: Copy Stackdriver credentials
  become: true
  copy:
    src: gcp_stackdriver_credentials.json
    dest: "{{ gcp_stackdriver_credentials_path }}"
    owner: root
    group: root
    mode: 0400
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Set GCP Project ID environment variable
  become: true
  lineinfile:
    path: /etc/environment
    line: "GOOGLE_CLOUD_PROJECT={{ gcp_project_id }}"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Set Stackdriver credentials environment variable
  become: true
  lineinfile:
    path: /etc/environment
    line: "GOOGLE_APPLICATION_CREDENTIALS={{ gcp_stackdriver_credentials_path }}"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
