---
- name: Install frontend dependencies
  command: "npm i --production"
  args:
    chdir: "{{ frontend_project_path }}"
    creates: "{{ frontend_project_path }}/node_modules"

- name: Build frontend
  command: "npm run build"
  args:
    chdir: "{{ frontend_project_path }}"
    creates: "{{ frontend_project_path }}/build/index.html"
  environment:
    REACT_APP_API_ENDPOINT: "https://{{ domain_name }}"
    REACT_APP_PROJECT_URL: "https://github.com/ayltai/hknews-web"

- name: Copy frontend artifacts to backend
  copy:
    src: "{{ frontend_project_path }}/*"
    dest: "{{ backend_project_path }}/src/main/resources/public"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Build backend
  command: "{{ backend_project_path }}/build.sh"
  args:
    chdir: "{{ backend_project_path }}"
    creates: "{{ backend_project_path }}/build/libs/hknews-backend-1.0.0.jar"
