---
- name: Create artifact directory
  file:
    path: "{{ project_path }}/build/libs"
    state: directory
    mode: 755
    recurse: yes

- name: Download artifacts list
  command: "wget $(curl https://circleci.com/api/v1.1/project/github/ayltai/hknews-backend/latest/artifacts?circle-token={{ circleci_token }} | jq -r '.[0].url')"
  args:
    chdir: "{{ project_path }}/build/libs"
    creates: "{{ project_path }}/build/libs/hknews-backend-1.0.0.jar"
