---
- name: Copy SSL certificate
  become: true
  copy:
    src: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
    dest: "{{ project_path }}/keystore.pem"
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Copy private key file
  become: true
  copy:
    src: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
    dest: "{{ project_path }}/private.key"
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Generate P12 certificate
  become: true
  command: |
    openssl pkcs12 \
    -export \
    -in /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem \
    -inkey /etc/letsencrypt/live/{{ domain_name }}/privkey.pem \
    -password pass:{{ ssl_key }}
    -out {{ project_path }}/keystore.p12 \
    -name keystore
  args:
    creates: "{{ project_path }}/keystore.p12"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Gererate JKS certificate
  become: true
  command: |
    keytool \
    -importkeystore \
    -deststorepass {{ ssl_key }} \
    -destkeypass {{ ssl_key }} \
    -destkeystore {{ project_path }}/keystore.jks \
    -srckeystore {{ project_path }}/keystore.p12 \
    -srcstoretype PKCS12 \
    -srcstorepass {{ ssl_key }} \
    -alias keystore
  args:
    creates: "{{ project_path }}/keystore.jks"

- name: Create artifact directory
  file:
    path: "{{ project_path }}/build/libs"
    state: directory
    mode: 0755
    recurse: yes

- name: Copy script to remote host
  copy:
    src: download.sh
    dest: "{{ project_path }}/build/libs/download.sh"

- name: Download artifact
  shell: download.sh
  args:
    chdir: "{{ project_path }}/build/libs/"
    creates: "{{ project_path }}/build/libs/hknews-backend-1.0.0.jar"
  environment:
    CIRCLECI_TOKEN: "{{ circleci_token }}"
