---
- name: Generate P12 certificate
  become: true
  command: |
    openssl pkcs12 \
    -export \
    -in /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem \
    -inkey /etc/letsencrypt/live/{{ domain_name }}/privkey.pem \
    -password pass:{{ ssl_key }}
    -out {{ backend_project_path }}/keystore.p12 \
    -name keystore
  args:
    creates: "{{ backend_project_path }}/keystore.p12"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Gererate JKS certificate
  become: true
  command: |
    keytool \
    -importkeystore \
    -deststorepass {{ ssl_key }} \
    -destkeypass {{ ssl_key }} \
    -destkeystore {{ backend_project_path }}/keystore.jks \
    -srckeystore {{ backend_project_path }}/keystore.p12 \
    -srcstoretype PKCS12 \
    -srcstorepass {{ ssl_key }} \
    -alias keystore
  args:
    creates: "{{ backend_project_path }}/keystore.jks"
