---
- name: Copy Prometheus configuration file
  become: true
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Prometheus
    - Restart Prometheus MongoDB Exporter
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
