---
- name: Install Prometheus packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - prometheus
      - prometheus-node-exporter
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
