---
- name: setup
  hosts: hknews
  become: true
  tasks:
    - name: initialize
      include_role:
        name: initialize
    - name: letsencrypt
      include_role:
        name: letsencrypt
    - name: git
      include_role:
        name: git
    - name: java
      include_role:
        name: java
    - name: mongodb
      include_role:
        name: mongodb
    - name: node
      include_role:
        name: node
    - name: pm2
      include_role:
        name: pm2
    - name: fail2ban
      include_role:
        name: fail2ban
    - name: prometheus
      include_role:
        name: prometheus
    - name: grafana
      include_role:
        name: grafana
    - name: app
      include_role:
        name: app
    - name: cleanup
      include_role:
        name: cleanup
  vars:
    domain_name: hknews.dev
    project_path: /home/ubuntu/projects/hknews-backend
    project_repo: https://github.com/ayltai/hknews-backend.git
    email: ayltai@gmail.com
